server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    root   /usr/share/nginx/html;

    location / {
        index  index.html index.htm;
    }

    # Configuration to handle specific Unity compressed file types with Gzip
    location ~ \.js\.gz$ {
        gzip off;
        add_header Content-Encoding gzip;
        add_header Content-Type application/javascript;
    }
    location ~ \.wasm\.gz$ {
        gzip off;
        add_header Content-Encoding gzip;
        default_type application/wasm;
    }
    location ~ \.data\.gz$ {
        gzip off;
        add_header Content-Encoding gzip;
        default_type application/octet-stream;
    }
}
